# PyTorch & Hugging Face Setup for NVIDIA RTX 50 Series GPUs


This notebook demonstrates how to set up and use PyTorch with NVIDIA RTX 5090 GPU,
including basic tensor operations and Hugging Face model inference.

Requirements:
- NVIDIA RTX 50 series GPU
- Ubuntu 24.04 LTS
- NVIDIA Driver 570.86.16 or later


Downloads NVIDIA drivers by going here [https://www.nvidia.com/en-us/drivers/](https://www.nvidia.com/en-us/drivers/) and download .run file


### Installing PyTorch, Torchvision, and Torchaudio

In [1]:
!pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
!pip install soundfile

Looking in indexes: https://download.pytorch.org/whl/nightly/cu128


In [2]:
import torch

# Test PyTorch installation
print("PyTorch version:", torch.__version__)

PyTorch version: 2.8.0.dev20250622+cu128


In [3]:
# Check if CUDA (GPU) is available
if torch.cuda.is_available():
    device = torch.device("cuda")  # Use GPU
    print("CUDA is available! Using GPU.")
else:
    device = torch.device("cpu")  # Use CPU
    print("CUDA is not available. Using CPU.")

# Create a tensor
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print("Tensor x:\n", x)

# Perform basic operations
y = x + 2
print("Tensor y (x + 2):\n", y)

z = torch.matmul(x, y)
print("Matrix multiplication (x @ y):\n", z)

CUDA is available! Using GPU.
Tensor x:
 tensor([[1., 2.],
        [3., 4.]])
Tensor y (x + 2):
 tensor([[3., 4.],
        [5., 6.]])
Matrix multiplication (x @ y):
 tensor([[13., 16.],
        [29., 36.]])


In [4]:
import torchaudio
import torchvision

# Print versions to verify installation
print(f"Torchaudio version: {torchaudio.__version__}")
print(f"Torchvision version: {torchvision.__version__}")

Torchaudio version: 2.8.0.dev20250622+cu128
Torchvision version: 0.23.0.dev20250622+cu128


In [2]:
# Basic audio loading test
file = torchaudio.utils.download_asset("tutorial-assets/Lab41-SRI-VOiCES-rm1-babb-mc01-stu-clo-8000hz.wav")
waveform, sample_rate = torchaudio.load(file) 
print(f"\nAudio shape: {waveform.shape}")
print(f"Sample rate: {sample_rate}")

# Basic image loading test
from torchvision import datasets
train_data = datasets.MNIST(
    root = 'data',
    train = True,
    download = True
)
print(f"\nMNIST Dataset size: {len(train_data)}")



Audio shape: torch.Size([1, 40000])
Sample rate: 8000


100.0%
100.0%
100.0%
100.0%


MNIST Dataset size: 60000


### Installing Hugging Face

In [5]:
!pip install transformers accelerate "huggingface_hub[cli]"

  Using cached transformers-4.52.4-py3-none-any.whl.metadata (38 kB)
  Using cached accelerate-1.8.1-py3-none-any.whl.metadata (19 kB)
  Using cached huggingface_hub-0.33.0-py3-none-any.whl.metadata (14 kB)
  Using cached regex-2024.11.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
  Using cached tokenizers-0.21.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
  Using cached safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
  Using cached hf_xet-1.1.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (879 bytes)
  Using cached InquirerPy-0.3.4-py3-none-any.whl.metadata (8.1 kB)
  Using cached pfzy-0.3.4-py3-none-any.whl.metadata (4.9 kB)
Using cached transformers-4.52.4-py3-none-any.whl (10.5 MB)
Using cached accelerate-1.8.1-py3-none-any.whl (365 kB)
Using cached InquirerPy-0.3.4-py3-none-any.whl (67 kB)
Usin

Load and test Hugging Face by running Llama 3.2 Model

In [6]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.2-3B", 
                                             device_map="auto", 
                                             torch_dtype=torch.float16)
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-3B")
inputs = tokenizer("Explain GPU acceleration:", return_tensors="pt").to("cuda")
outputs = model.generate(**inputs, max_new_tokens=100)
print(tokenizer.decode(outputs[0]))


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


<|begin_of_text|>Explain GPU acceleration: GPU stands for graphics processing unit. It is a specialized electronic circuit designed to rapidly manipulate and alter memory to accelerate the creation of images in a frame buffer intended for output to a display device. These processors are used in embedded systems such as mobile phones, video game consoles, and personal computers. GPUs are very efficient at manipulating computer graphics, and are therefore used for 3D graphics applications such as video games and interactive 3D applications. GPUs are used in other applications such as video encoding, video
